### PR TITLE
modernize name in readme

### PR DESCRIPTION
**Pull request by nolenroyalty**
update name to increase popularity

### CODE REVIEW

**Comment by momo-sa** [comment]
lol

**Comment by eliothedeman** [comment]
Giving this serious consideration.

**Comment by amwelch** [comment]
:+1: this is a serious issue and I would appreciate if the maintainers would deliver a speedy decision. I would love to integrate this software at the company where I work, but nobody takes it seriously after looking at the docs.

**Comment by amwelch** [comment]
I realize you guys are busy, but we still don't have a decision on this pr. Please review ASAP.

**Comment by nolenroyalty** [comment]
you also seem to have deleted my issues requesting a picture of Skrillex to be used as ~~Bangarang's~~ Scary Monsters and Nice Sprites's official icon.  This is concerning behavior unbecoming of an application owner and maintainer.

**Comment by amwelch** [comment]
I'm also concerned about https://github.com/eliothedeman/bangarang/issues/80. While Nolen may indeed have a bug it is not within the scope of "Scary Monsters and Nice Sprites" (trademark pending) to attempt to fix anything wrong with Nolen v1.

**Pull request closed without merging**
